export const dietOptions = ['Any', 'Vegetarian', 'Vegan', 'Pescetarian', 'Gluten free', 'Low FODMAP']
export const cuisineOptions = [
    'Any', 
    'African', 
    'Asian', 
    'American', 
    'British', 
    'Cajun', 
    'Caribbean',
    'Chinese',
    'Eastern European',
    'French',
    'German',
    'Greek',
    'Indian',
    'Italian',
    'Japanese',
    'Korean',
    'Latin American',
    'Mexican',
    'Middle Eastern',
    'Nordic',
    'Spanish',
    'Thai',
    'Vietnamese'
]